name: 🚀 Deploy 3.0.0-alpha.1

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: libhal/ci/.github/workflows/deploy.yml@5.x.y
    with:
      compiler: gcc
      version: 3.0.0-alpha.1
      arch: x86_64
      compiler_version: 12.3
      compiler_package: ""
      os: Linux
    secrets: inherit
